name: Check Commit Message for Text

on:
  push:
    branches:
      - '**'  # Trigger on any push to any branch
  pull_request:
    branches:
      - '**'  # Trigger on any pull request to any branch

jobs:
  check-commit-message:
    runs-on: ubuntu-latest  # You can change to windows-latest or macos-latest if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Ensure Git has history to detect changes

      - name: Debug Commit Message
        run: |
          echo "Commit SHA: ${{ github.sha }}"
          echo "Commit Message: ${{ github.event.head_commit.message }}"

      - name: Check Commit Message for 'Updated GitHub Repo'
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          REQUIRED_TEXT="Updated GitHub Repo"
          
          if [[ "$COMMIT_MSG" != *"$REQUIRED_TEXT"* ]]; then
            echo "❌ Commit message does not contain the required text: '$REQUIRED_TEXT'."
            exit 1  # Force GitHub Actions to FAIL if the required text is missing
          fi
          
          echo "✅ Commit message contains the required text: '$REQUIRED_TEXT'."
