name: Simple CI Workflow

on:
  push:
    branches:
      - '**'  # Trigger on any push to any branch
  pull_request:
    branches:
      - '**'  # Trigger on any pull request to any branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can change this to windows-latest or macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Add any specific steps for your project, such as:
      # - Running tests
      # - Building your project
      # - Deploying
      # For example, here's a simple placeholder step:
      - name: Run a Command
        run: |
          echo "Run your build/test commands here"
