name: Check Commit Message for "GitHub"

on:
  push:
    branches:
      - main  # Triggers when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Triggers on pull requests to the main branch

jobs:
  check-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if commit message contains "GitHub"
        id: check-commit-message
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          
          if [[ "$COMMIT_MSG" == *"GitHub"* ]]; then
            echo "✅ Commit message contains 'GitHub'. Workflow successful."
          else
            echo "❌ Commit message does not contain 'GitHub'. Failing workflow."
            exit 1  # Fail the workflow if the message doesn't contain 'GitHub'
          fi
